# Generated by Django 4.2.4 on 2023-08-25 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Palette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominant_color_1', models.CharField(max_length=6)),
                ('dominant_color_2', models.CharField(blank=True, max_length=6, null=True)),
                ('accent_color_1', models.CharField(max_length=6)),
                ('accent_color_2', models.CharField(max_length=6)),
                ('accent_color_3', models.CharField(blank=True, max_length=6, null=True)),
                ('accent_color_4', models.CharField(blank=True, max_length=6, null=True)),
                ('name', models.CharField(max_length=50)),
                ('is_public', models.BooleanField(default=False)),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palettes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
